esphome:
  name: depth_gauge
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: " Init Hotspot"
    ap_timeout: 20s
    password: !secret wifi_ap_pass

captive_portal:

# Enable logging
logger:

ota:
  password: !secret ota_pass
